"use client";

import { FormEvent, useMemo, useState } from "react";
import { Icon } from "@/components/Icon";
import { EmptyState, ErrorState, LoadingState, PageIntro, SearchField, StatusPill } from "@/components/ui";
import { apiFetch } from "@/lib/api-client";
import type { Faq, LocalizedText, Page } from "@/lib/types";
import { useRemoteData } from "@/lib/use-remote-data";

const empty = (): LocalizedText => ({ en: "", de: "", es: "", fr: "" });
export function AdminFaqsPage() {
  const query = useRemoteData<Page<Faq>>("admin/faqs?page=1&pageSize=100");
  const [search, setSearch] = useState(""); const [editing, setEditing] = useState<Faq | "new" | null>(null); const [question, setQuestion] = useState(empty()); const [answer, setAnswer] = useState(empty()); const [section, setSection] = useState("general"); const [published, setPublished] = useState(false); const [busy, setBusy] = useState(false);
  const items = useMemo(() => (query.data?.items ?? []).filter((item) => `${item.section} ${Object.values(item.question).join(" ")}`.toLowerCase().includes(search.toLowerCase())), [query.data, search]);
  function choose(item?: Faq) { setEditing(item ?? "new"); setQuestion(item ? { ...item.question } : empty()); setAnswer(item ? { ...item.answer } : empty()); setSection(item?.section ?? "general"); setPublished(item?.published ?? false); }
  function reset() { setEditing(null); setQuestion(empty()); setAnswer(empty()); setSection("general"); setPublished(false); }
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); const body = { question, answer, section: section.trim(), published, order: editing && editing !== "new" ? editing.order : query.data?.items.length ?? 0 }; try { if (editing === "new") await apiFetch("admin/faqs", { method: "POST", body: JSON.stringify(body) }); else if (editing) await apiFetch(`admin/faqs/${editing._id}`, { method: "PATCH", body: JSON.stringify(body) }); reset(); await query.reload(); } catch (error) { window.alert(error instanceof Error ? error.message : "Unable to save FAQ."); } finally { setBusy(false); } }
  async function remove(item: Faq) { if (!window.confirm(`Delete “${item.question.en}”?`)) return; await apiFetch(`admin/faqs/${item._id}`, { method: "DELETE" }); await query.reload(); }
  return <><PageIntro title="FAQs" description="Manage the questions and answers shown in the mobile app." action={<button className="button button-primary" onClick={() => choose()}><Icon name="plus" />Add FAQ</button>} /><div className="toolbar"><SearchField value={search} onChange={setSearch} placeholder="Search FAQs" /><button className="button button-primary admin-mobile-only" onClick={() => choose()}><Icon name="plus" />Add FAQ</button></div>{editing ? <form className="card native-settings-form" onSubmit={save}><div className="card-header"><h3>{editing === "new" ? "Add FAQ" : "Edit FAQ"}</h3></div><div className="card-body form-grid"><label className="full"><span>Section</span><input value={section} onChange={(event) => setSection(event.target.value)} required /></label>{(["en","de","es","fr"] as const).map((locale) => <div className="full native-faq-locale" key={locale}><strong>{locale.toUpperCase()}</strong><label><span>Question</span><input value={question[locale]} onChange={(event) => setQuestion((value) => ({ ...value, [locale]: event.target.value }))} required /></label><label><span>Answer</span><textarea value={answer[locale]} onChange={(event) => setAnswer((value) => ({ ...value, [locale]: event.target.value }))} required /></label></div>)}<label className="full native-switch-row"><span>Published</span><input type="checkbox" checked={published} onChange={(event) => setPublished(event.target.checked)} /></label><div className="full native-form-actions"><button type="button" className="button button-secondary" onClick={reset}>Cancel</button><button className="button button-primary" disabled={busy}>{busy ? "Saving…" : "Save"}</button></div></div></form> : null}{query.loading ? <LoadingState /> : query.error ? <ErrorState message={query.error} retry={query.reload} /> : !items.length ? <EmptyState title="No FAQs found" /> : <section className="native-faq-list">{items.map((item) => <article className="card" key={item._id}><div><strong>{item.question.en}</strong><small>{item.section}</small></div><StatusPill value={item.published ? "active" : "draft"} /><div><button onClick={() => choose(item)} aria-label={`Edit ${item.question.en}`}><Icon name="edit" /></button><button onClick={() => remove(item)} aria-label={`Delete ${item.question.en}`}><Icon name="trash" /></button></div></article>)}</section>}</>;
}
